apiVersion: v1
kind: Service
metadata:
  name: {{ template "stellar-horizon.fullname" . }}-http
  labels:
    app: {{ template "stellar-horizon.name" . }}
    chart: {{ template "stellar-horizon.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.httpService.type }}
  ports:
    - port: {{ .Values.httpService.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{ template "stellar-horizon.name" . }}
    release: {{ .Release.Name }}
