apiVersion: v1
kind: Service
metadata:
  name: {{ template "stellar-horizon.fullname" . }}-horizon
  labels:
    app: {{ template "stellar-horizon.name" . }}
    chart: {{ template "stellar-horizon.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.horizonService.type }}
  ports:
    - port: {{ .Values.horizonService.port }}
      targetPort: horizon
      protocol: TCP
      name: horizon
  {{- with .Values.horizonService.loadBalancerIP }}
  loadBalancerIP: {{ . }}
  {{- end }}
  {{- with .Values.horizonService.externalTrafficPolicy }}
  externalTrafficPolicy: {{ . }}
  {{- end }}
  selector:
    app: {{ template "stellar-horizon.name" . }}
    release: {{ .Release.Name }}
